Mark the build as borken if it's WIP
Since that indicates a logic problem with the build script or circle
config.

diff --git a/circle.yml b/circle.yml
--- a/circle.yml
+++ b/circle.yml
@@ -24,6 +24,11 @@ dependencies:
 
 test:
   override:
+    - |
+        cd $SRCDIR; if [ $(./image-tag --show-diff | grep -e '-WIP$') ]; then
+           echo "WIP build; exiting with error to mark as a failure"
+           exit 1
+        fi
     - cd $SRCDIR; make RM= lint
     - cd $SRCDIR; COVERDIR=./coverage make RM= test
     - cd $SRCDIR; make RM=
@@ -43,5 +48,4 @@ deployment:
     branch: master
     commands:
       - docker login -e '.' -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PASSWORD" quay.io
-      - ./image-tag 2>/dev/null | if [ $(grep -c -e '-WIP$') != '0' ]; then echo "WIP build; bailing" && exit 1; fi
       - ./push-images
